"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
}

export interface Translations {
  [key: string]: string;
}

export interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  t: (key: string) => string;
  languages: Language[];
}

const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ar', name: 'العربية', flag: '🇦🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
];

// Translation data
const translations: Record<string, Translations> = {
  en: {
    // Navigation
    'nav.buy': 'Buy',
    'nav.rent': 'Rent',
    'nav.projects': 'Projects',
    'nav.teams': 'Teams',
    'nav.areas': 'Areas',
    'nav.services': 'Services',
    'nav.blogs': 'Blogs',
    'nav.more': 'More',
    'nav.listYourProperty': 'List Your Property',
    
    // Services
    'services.propertyManagement': 'Property Management',
    'services.mortgages': 'Mortgages',
    'services.conveyancing': 'Conveyancing',
    'services.shortTermRentals': 'Short Term Rentals',
    'services.propertySnagging': 'Property Snagging',
    'services.partnerProgram': 'Partner Program',
    
    // Team page
    'team.loading': 'Loading team members...',
    'team.title': 'Meet Our Team',
    'team.subtitle': 'Discover our exceptional team of luxury real estate professionals in Dubai. Expert agents dedicated to making your property dreams come true.',
    'team.management': 'Management',
    'team.brokers': 'Brokers',
    'team.showing': 'Showing',
    'team.teamMembers': 'team members',
    'team.languages': 'Languages',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menu',
    
    // Footer
    'footer.newsletter': 'Receive our exceptional real estate listings delivered straight to your inbox.',
    'footer.emailLabel': 'Email address for newsletter subscription',
    'footer.emailPlaceholder': 'Enter your email address',
    'footer.subscribe': 'Subscribe',
    'footer.sitemap': 'Sitemap',
    'footer.contact': 'Contact',
    'footer.whyDubai': 'Why Dubai',
    'footer.contactUs': 'Contact Us',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Completion Status',
    'buy.completedSecondary': 'Completed Secondary',
    'buy.completedPrimary': 'Completed Primary',
    'buy.propertyType': 'Property Type',
    'buy.minPrice': 'Min Price',
    'buy.maxPrice': 'Max Price',
    'buy.location': 'City, building or community',
    'buy.type': 'Type',
    'buy.buy': 'Buy',
    'buy.rent': 'Rent',

    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  ar: {
    // Navigation
    'nav.buy': 'شراء',
    'nav.rent': 'إيجار',
    'nav.projects': 'مشاريع',
    'nav.teams': 'فرق العمل',
    'nav.areas': 'المناطق',
    'nav.services': 'الخدمات',
    'nav.blogs': 'المدونات',
    'nav.more': 'المزيد',
    'nav.listYourProperty': 'أدرج عقارك',
    
    // Services
    'services.propertyManagement': 'إدارة العقارات',
    'services.mortgages': 'الرهون العقارية',
    'services.conveyancing': 'التنازل القانوني',
    'services.shortTermRentals': 'الإيجار قصير المدى',
    'services.propertySnagging': 'فحص العقارات',
    'services.partnerProgram': 'برنامج الشراكة',
    
    // Team page
    'team.loading': 'جاري تحميل أعضاء الفريق...',
    'team.title': 'تعرف على فريقنا',
    'team.subtitle': 'اكتشف فريقنا الاستثنائي من محترفي العقارات الفاخرة في دبي. وكلاء خبراء ملتزمون بتحقيق أحلامك العقارية.',
    'team.management': 'الإدارة',
    'team.brokers': 'الوسطاء',
    'team.showing': 'عرض',
    'team.teamMembers': 'أعضاء الفريق',
    'team.languages': 'اللغات',
    
    // Common
    'common.currency': 'درهم',
    'common.menu': 'القائمة',
    
    // Footer
    'footer.newsletter': 'احصل على قوائم العقارات الاستثنائية لدينا مباشرة في صندوق الوارد الخاص بك.',
    'footer.emailLabel': 'عنوان البريد الإلكتروني للاشتراك في النشرة الإخبارية',
    'footer.emailPlaceholder': 'أدخل عنوان بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'footer.sitemap': 'خريطة الموقع',
    'footer.contact': 'اتصل بنا',
    'footer.whyDubai': 'لماذا دبي',
    'footer.contactUs': 'اتصل بنا',
    
    // Hero
    'hero.companyName': 'موداك العقارية',
    
    // Buy page
    'buy.completionStatus': 'حالة الإنجاز',
    'buy.completedSecondary': 'مكتمل ثانوي',
    'buy.completedPrimary': 'مكتمل أساسي',
    'buy.propertyType': 'نوع العقار',
    'buy.minPrice': 'الحد الأدنى للسعر',
    'buy.maxPrice': 'الحد الأقصى للسعر',
    'buy.location': 'المدينة، المبنى أو المجتمع',
    'buy.type': 'النوع',
    'buy.buy': 'شراء',
    'buy.rent': 'إيجار',

    // Off Plans page
    'offplans.completionStatus': 'حالة الإنجاز',
    'offplans.completedSecondary': 'مكتمل ثانوي',
    'offplans.offPlanSecondary': 'خارج الخطة الثانوية',
    'offplans.completedPrimary': 'مكتمل أساسي',
    'offplans.offPlanPrimary': 'خارج الخطة الأساسية',
    'offplans.propertyType': 'نوع العقار',
    'offplans.apartment': 'شقة',
    'offplans.villa': 'فيلا',
    'offplans.townhouse': 'تاون هاوس',
    'offplans.penthouse': 'بنتهاوس',
    'offplans.studio': 'استوديو',
    'offplans.bedrooms': 'غرف النوم',
    'offplans.oneBedroom': 'غرفة نوم واحدة',
    'offplans.twoBedrooms': 'غرفتان نوم',
    'offplans.threeBedrooms': '3 غرف نوم',
    'offplans.fourBedrooms': '4 غرف نوم',
    'offplans.fivePlusBedrooms': '5+ غرف نوم',
    'offplans.bathrooms': 'الحمامات',
    'offplans.oneBathroom': 'حمام واحد',
    'offplans.twoBathrooms': 'حمامان',
    'offplans.threeBathrooms': '3 حمامات',
    'offplans.fourBathrooms': '4 حمامات',
    'offplans.fivePlusBathrooms': '5+ حمامات',
    'offplans.year': 'السنة',
    'offplans.handoverYear': 'سنة التسليم',
    'offplans.minPrice': 'الحد الأدنى للسعر',
    'offplans.maxPrice': 'الحد الأقصى للسعر',
    'offplans.locationPlaceholder': 'المدينة، المبنى أو المجتمع',
    'offplans.type': 'النوع',
    'offplans.buy': 'شراء',
    'offplans.rent': 'إيجار',
    'offplans.offPlan': 'خارج الخطة',
    'offplans.location': 'الموقع',
    'offplans.developer': 'المطور',
    'offplans.searchDevelopers': 'ابحث عن المطورين...',
    'offplans.searchProperties': 'بحث عن العقارات',
    'offplans.moreFilters': 'المزيد من الفلاتر',
    'offplans.searchFilters': 'فلاتر البحث',
    'offplans.anyBedrooms': 'أي غرف نوم',
    'offplans.anyBathrooms': 'أي حمامات',
    'offplans.fivePlusBeds': '5+ أسرة',
    'offplans.bed': 'سرير',
    'offplans.fivePlusBaths': '5+ حمامات',
    'offplans.bath': 'حمام',
    'offplans.beds': 'أسرة',
    'offplans.learnMore': 'اعرف المزيد',
  },
  fr: {
    // Navigation
    'nav.buy': 'Acheter',
    'nav.rent': 'Louer',
    'nav.projects': 'Projets',
    'nav.teams': 'Équipes',
    'nav.areas': 'Zones',
    'nav.services': 'Services',
    'nav.blogs': 'Blogs',
    'nav.more': 'Plus',
    'nav.listYourProperty': 'Listez Votre Propriété',
    
    // Services
    'services.propertyManagement': 'Gestion Immobilière',
    'services.mortgages': 'Hypothèques',
    'services.conveyancing': 'Transfert de Propriété',
    'services.shortTermRentals': 'Locations Courtes Durées',
    'services.propertySnagging': 'Inspection Immobilière',
    'services.partnerProgram': 'Programme Partenaire',
    
    // Team page
    'team.loading': 'Chargement des membres de l\'équipe...',
    'team.title': 'Rencontrez Notre Équipe',
    'team.subtitle': 'Découvrez notre équipe exceptionnelle de professionnels de l\'immobilier de luxe à Dubaï. Des agents experts dédiés à la réalisation de vos rêves immobiliers.',
    'team.management': 'Gestion',
    'team.brokers': 'Courtiers',
    'team.showing': 'Affichage',
    'team.teamMembers': 'membres de l\'équipe',
    'team.languages': 'Langues',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menu',
    
    // Footer
    'footer.newsletter': 'Recevez nos listes immobilières exceptionnelles directement dans votre boîte de réception.',
    'footer.emailLabel': 'Adresse e-mail pour l\'abonnement à la newsletter',
    'footer.emailPlaceholder': 'Entrez votre adresse e-mail',
    'footer.subscribe': 'S\'abonner',
    'footer.sitemap': 'Plan du site',
    'footer.contact': 'Contact',
    'footer.whyDubai': 'Pourquoi Dubaï',
    'footer.contactUs': 'Nous contacter',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Statut d\'achèvement',
    'buy.completedSecondary': 'Terminé secondaire',
    'buy.completedPrimary': 'Terminé primaire',
    'buy.propertyType': 'Type de propriété',
    'buy.minPrice': 'Prix minimum',
    'buy.maxPrice': 'Prix maximum',
    'buy.location': 'Ville, bâtiment ou communauté',
    'buy.type': 'Type',
    'buy.buy': 'Acheter',
    'buy.rent': 'Louer',

    // Off Plans page
    'offplans.completionStatus': 'Statut d\'achèvement',
    'offplans.completedSecondary': 'Terminé secondaire',
    'offplans.offPlanSecondary': 'Hors Plan Secondaire',
    'offplans.completedPrimary': 'Terminé primaire',
    'offplans.offPlanPrimary': 'Hors Plan Primaire',
    'offplans.propertyType': 'Type de propriété',
    'offplans.apartment': 'Appartement',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Maison de ville',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Chambres',
    'offplans.oneBedroom': '1 Chambre',
    'offplans.twoBedrooms': '2 Chambres',
    'offplans.threeBedrooms': '3 Chambres',
    'offplans.fourBedrooms': '4 Chambres',
    'offplans.fivePlusBedrooms': '5+ Chambres',
    'offplans.bathrooms': 'Salles de bain',
    'offplans.oneBathroom': '1 Salle de bain',
    'offplans.twoBathrooms': '2 Salles de bain',
    'offplans.threeBathrooms': '3 Salles de bain',
    'offplans.fourBathrooms': '4 Salles de bain',
    'offplans.fivePlusBathrooms': '5+ Salles de bain',
    'offplans.year': 'Année',
    'offplans.handoverYear': 'Année de livraison',
    'offplans.minPrice': 'Prix minimum',
    'offplans.maxPrice': 'Prix maximum',
    'offplans.locationPlaceholder': 'Ville, bâtiment ou communauté',
    'offplans.type': 'Type',
    'offplans.buy': 'Acheter',
    'offplans.rent': 'Louer',
    'offplans.offPlan': 'Hors Plan',
    'offplans.location': 'Emplacement',
    'offplans.developer': 'Promoteur',
    'offplans.searchDevelopers': 'Rechercher des promoteurs...',
    'offplans.searchProperties': 'Rechercher des Propriétés',
    'offplans.moreFilters': 'Plus de Filtres',
    'offplans.searchFilters': 'Filtres de Recherche',
    'offplans.anyBedrooms': 'Toutes Chambres',
    'offplans.anyBathrooms': 'Toutes Salles de bain',
    'offplans.fivePlusBeds': '5+ Lits',
    'offplans.bed': 'Lit',
    'offplans.fivePlusBaths': '5+ Salles de bain',
    'offplans.bath': 'Bain',
    'offplans.beds': 'Lits',
    'offplans.learnMore': 'En Savoir Plus',
  },
  es: {
    // Navigation
    'nav.buy': 'Comprar',
    'nav.rent': 'Alquilar',
    'nav.projects': 'Proyectos',
    'nav.teams': 'Equipos',
    'nav.areas': 'Áreas',
    'nav.services': 'Servicios',
    'nav.blogs': 'Blogs',
    'nav.more': 'Más',
    'nav.listYourProperty': 'Lista Tu Propiedad',
    
    // Services
    'services.propertyManagement': 'Gestión de Propiedades',
    'services.mortgages': 'Hipotecas',
    'services.conveyancing': 'Transferencia de Propiedad',
    'services.shortTermRentals': 'Alquileres a Corto Plazo',
    'services.propertySnagging': 'Inspección de Propiedades',
    'services.partnerProgram': 'Programa de Socios',
    
    // Team page
    'team.loading': 'Cargando miembros del equipo...',
    'team.title': 'Conoce Nuestro Equipo',
    'team.subtitle': 'Descubre nuestro equipo excepcional de profesionales inmobiliarios de lujo en Dubái. Agentes expertos dedicados a hacer realidad tus sueños inmobiliarios.',
    'team.management': 'Gestión',
    'team.brokers': 'Corredores',
    'team.showing': 'Mostrando',
    'team.teamMembers': 'miembros del equipo',
    'team.languages': 'Idiomas',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menú',
    
    // Footer
    'footer.newsletter': 'Recibe nuestras listas inmobiliarias excepcionales directamente en tu bandeja de entrada.',
    'footer.emailLabel': 'Dirección de correo electrónico para suscripción al boletín',
    'footer.emailPlaceholder': 'Ingresa tu dirección de correo electrónico',
    'footer.subscribe': 'Suscribirse',
    'footer.sitemap': 'Mapa del sitio',
    'footer.contact': 'Contacto',
    'footer.whyDubai': 'Por qué Dubái',
    'footer.contactUs': 'Contáctanos',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Estado de finalización',
    'buy.completedSecondary': 'Completado secundario',
    'buy.completedPrimary': 'Completado primario',
    'buy.propertyType': 'Tipo de propiedad',
    'buy.minPrice': 'Precio mínimo',
    'buy.maxPrice': 'Precio máximo',
    'buy.location': 'Ciudad, edificio o comunidad',
    'buy.type': 'Tipo',
    'buy.buy': 'Comprar',
    'buy.rent': 'Alquilar',

    // Off Plans page (copying English for now)
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  de: {
    // Navigation
    'nav.buy': 'Kaufen',
    'nav.rent': 'Mieten',
    'nav.projects': 'Projekte',
    'nav.teams': 'Teams',
    'nav.areas': 'Bereiche',
    'nav.services': 'Dienstleistungen',
    'nav.blogs': 'Blogs',
    'nav.more': 'Mehr',
    'nav.listYourProperty': 'Ihre Immobilie Auflisten',
    
    // Services
    'services.propertyManagement': 'Immobilienverwaltung',
    'services.mortgages': 'Hypotheken',
    'services.conveyancing': 'Eigentumsübertragung',
    'services.shortTermRentals': 'Kurzzeitmieten',
    'services.propertySnagging': 'Immobilieninspektion',
    'services.partnerProgram': 'Partnerprogramm',
    
    // Team page
    'team.loading': 'Teammitglieder werden geladen...',
    'team.title': 'Lernen Sie Unser Team Kennen',
    'team.subtitle': 'Entdecken Sie unser außergewöhnliches Team von Luxus-Immobilienprofis in Dubai. Expertenmakler, die sich der Verwirklichung Ihrer Immobilienträume widmen.',
    'team.management': 'Verwaltung',
    'team.brokers': 'Makler',
    'team.showing': 'Anzeigen',
    'team.teamMembers': 'Teammitglieder',
    'team.languages': 'Sprachen',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menü',
    
    // Footer
    'footer.newsletter': 'Erhalten Sie unsere außergewöhnlichen Immobilienlisten direkt in Ihrem Posteingang.',
    'footer.emailLabel': 'E-Mail-Adresse für Newsletter-Anmeldung',
    'footer.emailPlaceholder': 'Geben Sie Ihre E-Mail-Adresse ein',
    'footer.subscribe': 'Abonnieren',
    'footer.sitemap': 'Sitemap',
    'footer.contact': 'Kontakt',
    'footer.whyDubai': 'Warum Dubai',
    'footer.contactUs': 'Kontaktieren Sie uns',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Fertigstellungsstatus',
    'buy.completedSecondary': 'Fertiggestellt sekundär',
    'buy.completedPrimary': 'Fertiggestellt primär',
    'buy.propertyType': 'Immobilientyp',
    'buy.minPrice': 'Mindestpreis',
    'buy.maxPrice': 'Höchstpreis',
    'buy.location': 'Stadt, Gebäude oder Gemeinde',
    'buy.type': 'Typ',
    'buy.buy': 'Kaufen',
    'buy.rent': 'Mieten',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  it: {
    // Navigation
    'nav.buy': 'Acquista',
    'nav.rent': 'Affitta',
    'nav.projects': 'Progetti',
    'nav.teams': 'Team',
    'nav.areas': 'Aree',
    'nav.services': 'Servizi',
    'nav.blogs': 'Blog',
    'nav.more': 'Altro',
    'nav.listYourProperty': 'Elenca La Tua Proprietà',
    
    // Services
    'services.propertyManagement': 'Gestione Immobiliare',
    'services.mortgages': 'Mutui',
    'services.conveyancing': 'Trasferimento Proprietà',
    'services.shortTermRentals': 'Affitti Brevi',
    'services.propertySnagging': 'Ispezione Immobiliare',
    'services.partnerProgram': 'Programma Partner',
    
    // Team page
    'team.loading': 'Caricamento membri del team...',
    'team.title': 'Incontra Il Nostro Team',
    'team.subtitle': 'Scopri il nostro team eccezionale di professionisti immobiliari di lusso a Dubai. Agenti esperti dedicati a realizzare i tuoi sogni immobiliari.',
    'team.management': 'Gestione',
    'team.brokers': 'Agenti',
    'team.showing': 'Mostrando',
    'team.teamMembers': 'membri del team',
    'team.languages': 'Lingue',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menu',
    
    // Footer
    'footer.newsletter': 'Ricevi le nostre eccezionali liste immobiliari direttamente nella tua casella di posta.',
    'footer.emailLabel': 'Indirizzo email per l\'iscrizione alla newsletter',
    'footer.emailPlaceholder': 'Inserisci il tuo indirizzo email',
    'footer.subscribe': 'Iscriviti',
    'footer.sitemap': 'Mappa del sito',
    'footer.contact': 'Contatto',
    'footer.whyDubai': 'Perché Dubai',
    'footer.contactUs': 'Contattaci',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Stato di completamento',
    'buy.completedSecondary': 'Completato secondario',
    'buy.completedPrimary': 'Completato primario',
    'buy.propertyType': 'Tipo di proprietà',
    'buy.minPrice': 'Prezzo minimo',
    'buy.maxPrice': 'Prezzo massimo',
    'buy.location': 'Città, edificio o comunità',
    'buy.type': 'Tipo',
    'buy.buy': 'Acquista',
    'buy.rent': 'Affitta',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  pt: {
    // Navigation
    'nav.buy': 'Comprar',
    'nav.rent': 'Alugar',
    'nav.projects': 'Projetos',
    'nav.teams': 'Equipes',
    'nav.areas': 'Áreas',
    'nav.services': 'Serviços',
    'nav.blogs': 'Blogs',
    'nav.more': 'Mais',
    'nav.listYourProperty': 'Liste Sua Propriedade',
    
    // Services
    'services.propertyManagement': 'Gestão de Propriedades',
    'services.mortgages': 'Hipotecas',
    'services.conveyancing': 'Transferência de Propriedade',
    'services.shortTermRentals': 'Aluguéis de Curto Prazo',
    'services.propertySnagging': 'Inspeção de Propriedades',
    'services.partnerProgram': 'Programa de Parceiros',
    
    // Team page
    'team.loading': 'Carregando membros da equipe...',
    'team.title': 'Conheça Nossa Equipe',
    'team.subtitle': 'Descubra nossa equipe excepcional de profissionais imobiliários de luxo em Dubai. Agentes especialistas dedicados a realizar seus sonhos imobiliários.',
    'team.management': 'Gestão',
    'team.brokers': 'Corretores',
    'team.showing': 'Mostrando',
    'team.teamMembers': 'membros da equipe',
    'team.languages': 'Idiomas',
    
    // Common
    'common.currency': 'AED',
    'common.menu': 'Menu',
    
    // Footer
    'footer.newsletter': 'Receba nossas listagens imobiliárias excepcionais diretamente na sua caixa de entrada.',
    'footer.emailLabel': 'Endereço de email para inscrição na newsletter',
    'footer.emailPlaceholder': 'Digite seu endereço de email',
    'footer.subscribe': 'Inscrever-se',
    'footer.sitemap': 'Mapa do site',
    'footer.contact': 'Contato',
    'footer.whyDubai': 'Por que Dubai',
    'footer.contactUs': 'Entre em contato',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Status de conclusão',
    'buy.completedSecondary': 'Concluído secundário',
    'buy.completedPrimary': 'Concluído primário',
    'buy.propertyType': 'Tipo de propriedade',
    'buy.minPrice': 'Preço mínimo',
    'buy.maxPrice': 'Preço máximo',
    'buy.location': 'Cidade, edifício ou comunidade',
    'buy.type': 'Tipo',
    'buy.buy': 'Comprar',
    'buy.rent': 'Alugar',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  ru: {
    // Navigation
    'nav.buy': 'Купить',
    'nav.rent': 'Арендовать',
    'nav.projects': 'Проекты',
    'nav.teams': 'Команды',
    'nav.areas': 'Районы',
    'nav.services': 'Услуги',
    'nav.blogs': 'Блоги',
    'nav.more': 'Больше',
    'nav.listYourProperty': 'Разместить Недвижимость',
    
    // Services
    'services.propertyManagement': 'Управление Недвижимостью',
    'services.mortgages': 'Ипотека',
    'services.conveyancing': 'Передача Права Собственности',
    'services.shortTermRentals': 'Краткосрочная Аренда',
    'services.propertySnagging': 'Инспекция Недвижимости',
    'services.partnerProgram': 'Партнерская Программа',
    
    // Team page
    'team.loading': 'Загрузка участников команды...',
    'team.title': 'Познакомьтесь с Нашей Командой',
    'team.subtitle': 'Откройте для себя нашу исключительную команду профессионалов элитной недвижимости в Дубае. Экспертные агенты, посвященные воплощению ваших мечтаний о недвижимости.',
    'team.management': 'Управление',
    'team.brokers': 'Брокеры',
    'team.showing': 'Показано',
    'team.teamMembers': 'участников команды',
    'team.languages': 'Языки',
    
    // Common
    'common.currency': 'Дирхам',
    'common.menu': 'Меню',
    
    // Footer
    'footer.newsletter': 'Получайте наши исключительные списки недвижимости прямо в ваш почтовый ящик.',
    'footer.emailLabel': 'Адрес электронной почты для подписки на рассылку',
    'footer.emailPlaceholder': 'Введите ваш адрес электронной почты',
    'footer.subscribe': 'Подписаться',
    'footer.sitemap': 'Карта сайта',
    'footer.contact': 'Контакты',
    'footer.whyDubai': 'Почему Дубай',
    'footer.contactUs': 'Связаться с нами',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'Статус завершения',
    'buy.completedSecondary': 'Завершено вторично',
    'buy.completedPrimary': 'Завершено первично',
    'buy.propertyType': 'Тип недвижимости',
    'buy.minPrice': 'Минимальная цена',
    'buy.maxPrice': 'Максимальная цена',
    'buy.location': 'Город, здание или сообщество',
    'buy.type': 'Тип',
    'buy.buy': 'Купить',
    'buy.rent': 'Арендовать',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  zh: {
    // Navigation
    'nav.buy': '购买',
    'nav.rent': '租赁',
    'nav.projects': '项目',
    'nav.teams': '团队',
    'nav.areas': '区域',
    'nav.services': '服务',
    'nav.blogs': '博客',
    'nav.more': '更多',
    'nav.listYourProperty': '列出您的房产',
    
    // Services
    'services.propertyManagement': '物业管理',
    'services.mortgages': '抵押贷款',
    'services.conveyancing': '产权转让',
    'services.shortTermRentals': '短期租赁',
    'services.propertySnagging': '房产检查',
    'services.partnerProgram': '合作伙伴计划',
    
    // Team page
    'team.loading': '正在加载团队成员...',
    'team.title': '认识我们的团队',
    'team.subtitle': '发现我们在迪拜的卓越豪华房地产专业团队。专业代理商致力于实现您的房地产梦想。',
    'team.management': '管理',
    'team.brokers': '经纪人',
    'team.showing': '显示',
    'team.teamMembers': '团队成员',
    'team.languages': '语言',
    
    // Common
    'common.currency': '迪拉姆',
    'common.menu': '菜单',
    
    // Footer
    'footer.newsletter': '将我们卓越的房地产列表直接发送到您的收件箱。',
    'footer.emailLabel': '新闻订阅的电子邮件地址',
    'footer.emailPlaceholder': '输入您的电子邮件地址',
    'footer.subscribe': '订阅',
    'footer.sitemap': '网站地图',
    'footer.contact': '联系方式',
    'footer.whyDubai': '为什么选择迪拜',
    'footer.contactUs': '联系我们',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': '完成状态',
    'buy.completedSecondary': '已完成次要',
    'buy.completedPrimary': '已完成主要',
    'buy.propertyType': '物业类型',
    'buy.minPrice': '最低价格',
    'buy.maxPrice': '最高价格',
    'buy.location': '城市、建筑或社区',
    'buy.type': '类型',
    'buy.buy': '购买',
    'buy.rent': '租赁',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  ja: {
    // Navigation
    'nav.buy': '購入',
    'nav.rent': '賃貸',
    'nav.projects': 'プロジェクト',
    'nav.teams': 'チーム',
    'nav.areas': 'エリア',
    'nav.services': 'サービス',
    'nav.blogs': 'ブログ',
    'nav.more': 'その他',
    'nav.listYourProperty': '物件を掲載',
    
    // Services
    'services.propertyManagement': 'プロパティ管理',
    'services.mortgages': '住宅ローン',
    'services.conveyancing': '不動産譲渡',
    'services.shortTermRentals': '短期賃貸',
    'services.propertySnagging': '物件検査',
    'services.partnerProgram': 'パートナープログラム',
    
    // Team page
    'team.loading': 'チームメンバーを読み込み中...',
    'team.title': '私たちのチームをご紹介',
    'team.subtitle': 'ドバイの豪華不動産プロフェッショナルの卓越したチームをご紹介します。あなたの不動産の夢を実現することに専念する専門エージェントです。',
    'team.management': '管理',
    'team.brokers': 'ブローカー',
    'team.showing': '表示中',
    'team.teamMembers': 'チームメンバー',
    'team.languages': '言語',
    
    // Common
    'common.currency': 'ディルハム',
    'common.menu': 'メニュー',
    
    // Footer
    'footer.newsletter': '私たちの卓越した不動産リストを直接あなたの受信箱にお届けします。',
    'footer.emailLabel': 'ニュースレター登録用のメールアドレス',
    'footer.emailPlaceholder': 'メールアドレスを入力してください',
    'footer.subscribe': '購読',
    'footer.sitemap': 'サイトマップ',
    'footer.contact': 'お問い合わせ',
    'footer.whyDubai': 'なぜドバイなのか',
    'footer.contactUs': 'お問い合わせ',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': '完成状況',
    'buy.completedSecondary': '完了セカンダリ',
    'buy.completedPrimary': '完了プライマリ',
    'buy.propertyType': '物件タイプ',
    'buy.minPrice': '最低価格',
    'buy.maxPrice': '最高価格',
    'buy.location': '都市、建物またはコミュニティ',
    'buy.type': 'タイプ',
    'buy.buy': '購入',
    'buy.rent': '賃貸',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  ko: {
    // Navigation
    'nav.buy': '구매',
    'nav.rent': '임대',
    'nav.projects': '프로젝트',
    'nav.teams': '팀',
    'nav.areas': '지역',
    'nav.services': '서비스',
    'nav.blogs': '블로그',
    'nav.more': '더보기',
    'nav.listYourProperty': '부동산 등록',
    
    // Services
    'services.propertyManagement': '부동산 관리',
    'services.mortgages': '모기지',
    'services.conveyancing': '부동산 양도',
    'services.shortTermRentals': '단기 임대',
    'services.propertySnagging': '부동산 검사',
    'services.partnerProgram': '파트너 프로그램',
    
    // Team page
    'team.loading': '팀 멤버 로딩 중...',
    'team.title': '우리 팀을 만나보세요',
    'team.subtitle': '두바이의 뛰어난 럭셔리 부동산 전문가 팀을 발견하세요. 귀하의 부동산 꿈을 실현하는 데 전념하는 전문 에이전트입니다.',
    'team.management': '관리',
    'team.brokers': '브로커',
    'team.showing': '표시 중',
    'team.teamMembers': '팀 멤버',
    'team.languages': '언어',
    
    // Common
    'common.currency': '디르함',
    'common.menu': '메뉴',
    
    // Footer
    'footer.newsletter': '우리의 탁월한 부동산 목록을 직접 받은 편지함으로 받아보세요.',
    'footer.emailLabel': '뉴스레터 구독용 이메일 주소',
    'footer.emailPlaceholder': '이메일 주소를 입력하세요',
    'footer.subscribe': '구독',
    'footer.sitemap': '사이트맵',
    'footer.contact': '연락처',
    'footer.whyDubai': '왜 두바이인가',
    'footer.contactUs': '문의하기',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': '완료 상태',
    'buy.completedSecondary': '완료 보조',
    'buy.completedPrimary': '완료 주요',
    'buy.propertyType': '부동산 유형',
    'buy.minPrice': '최저 가격',
    'buy.maxPrice': '최고 가격',
    'buy.location': '도시, 건물 또는 커뮤니티',
    'buy.type': '유형',
    'buy.buy': '구매',
    'buy.rent': '임대',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
  hi: {
    // Navigation
    'nav.buy': 'खरीदें',
    'nav.rent': 'किराया',
    'nav.projects': 'प्रोजेक्ट्स',
    'nav.teams': 'टीम्स',
    'nav.areas': 'क्षेत्र',
    'nav.services': 'सेवाएं',
    'nav.blogs': 'ब्लॉग्स',
    'nav.more': 'और',
    'nav.listYourProperty': 'अपनी प्रॉपर्टी लिस्ट करें',
    
    // Services
    'services.propertyManagement': 'प्रॉपर्टी मैनेजमेंट',
    'services.mortgages': 'मॉर्गेज',
    'services.conveyancing': 'प्रॉपर्टी ट्रांसफर',
    'services.shortTermRentals': 'शॉर्ट टर्म रेंटल्स',
    'services.propertySnagging': 'प्रॉपर्टी इंस्पेक्शन',
    'services.partnerProgram': 'पार्टनर प्रोग्राम',
    
    // Team page
    'team.loading': 'टीम मेम्बर्स लोड हो रहे हैं...',
    'team.title': 'हमारी टीम से मिलें',
    'team.subtitle': 'दुबई में लक्जरी रियल एस्टेट प्रोफेशनल्स की हमारी असाधारण टीम की खोज करें। आपके प्रॉपर्टी सपनों को साकार करने के लिए समर्पित विशेषज्ञ एजेंट।',
    'team.management': 'मैनेजमेंट',
    'team.brokers': 'ब्रोकर्स',
    'team.showing': 'दिखा रहे हैं',
    'team.teamMembers': 'टीम मेम्बर्स',
    'team.languages': 'भाषाएं',
    
    // Common
    'common.currency': 'दिरहम',
    'common.menu': 'मेनू',
    
    // Footer
    'footer.newsletter': 'हमारी असाधारण रियल एस्टेट सूचियों को सीधे अपने इनबॉक्स में प्राप्त करें।',
    'footer.emailLabel': 'न्यूज़लेटर सब्सक्रिप्शन के लिए ईमेल पता',
    'footer.emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
    'footer.subscribe': 'सब्सक्राइब करें',
    'footer.sitemap': 'साइटमैप',
    'footer.contact': 'संपर्क',
    'footer.whyDubai': 'दुबई क्यों',
    'footer.contactUs': 'हमसे संपर्क करें',
    
    // Hero
    'hero.companyName': 'MODAC PROPERTIES',
    
    // Buy page
    'buy.completionStatus': 'पूर्णता स्थिति',
    'buy.completedSecondary': 'पूर्ण माध्यमिक',
    'buy.completedPrimary': 'पूर्ण प्राथमिक',
    'buy.propertyType': 'संपत्ति प्रकार',
    'buy.minPrice': 'न्यूनतम मूल्य',
    'buy.maxPrice': 'अधिकतम मूल्य',
    'buy.location': 'शहर, भवन या समुदाय',
    'buy.type': 'प्रकार',
    'buy.buy': 'खरीदें',
    'buy.rent': 'किराया',
    // Off Plans page
    'offplans.completionStatus': 'Completion Status',
    'offplans.completedSecondary': 'Completed Secondary',
    'offplans.offPlanSecondary': 'Off Plan Secondary',
    'offplans.completedPrimary': 'Completed Primary',
    'offplans.offPlanPrimary': 'Off Plan Primary',
    'offplans.propertyType': 'Property Type',
    'offplans.apartment': 'Apartment',
    'offplans.villa': 'Villa',
    'offplans.townhouse': 'Townhouse',
    'offplans.penthouse': 'Penthouse',
    'offplans.studio': 'Studio',
    'offplans.bedrooms': 'Bedrooms',
    'offplans.oneBedroom': '1 Bedroom',
    'offplans.twoBedrooms': '2 Bedrooms',
    'offplans.threeBedrooms': '3 Bedrooms',
    'offplans.fourBedrooms': '4 Bedrooms',
    'offplans.fivePlusBedrooms': '5+ Bedrooms',
    'offplans.bathrooms': 'Bathrooms',
    'offplans.oneBathroom': '1 Bathroom',
    'offplans.twoBathrooms': '2 Bathrooms',
    'offplans.threeBathrooms': '3 Bathrooms',
    'offplans.fourBathrooms': '4 Bathrooms',
    'offplans.fivePlusBathrooms': '5+ Bathrooms',
    'offplans.year': 'Year',
    'offplans.handoverYear': 'Handover Year',
    'offplans.minPrice': 'Min Price',
    'offplans.maxPrice': 'Max Price',
    'offplans.locationPlaceholder': 'City, building or community',
    'offplans.type': 'Type',
    'offplans.buy': 'Buy',
    'offplans.rent': 'Rent',
    'offplans.offPlan': 'Off Plan',
    'offplans.location': 'Location',
    'offplans.developer': 'Developer',
    'offplans.searchDevelopers': 'Search developers...',
    'offplans.searchProperties': 'Search Properties',
    'offplans.moreFilters': 'More Filters',
    'offplans.searchFilters': 'Search Filters',
    'offplans.anyBedrooms': 'Any Bedrooms',
    'offplans.anyBathrooms': 'Any Bathrooms',
    'offplans.fivePlusBeds': '5+ Beds',
    'offplans.bed': 'Bed',
    'offplans.fivePlusBaths': '5+ Baths',
    'offplans.bath': 'Bath',
    'offplans.beds': 'Beds',
    'offplans.learnMore': 'Learn More',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  // Load saved language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage) {
      const language = languages.find(lang => lang.code === savedLanguage);
      if (language) {
        setCurrentLanguage(language);
      }
    }
  }, []);

  // Save language to localStorage when it changes
  const handleSetCurrentLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', language.code);
  };

  const t = (key: string): string => {
    const currentTranslations = translations[currentLanguage.code];
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setCurrentLanguage: handleSetCurrentLanguage,
        t,
        languages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
